### ISSUE TITLE
Add release tag

### ISSUE THREAD

**Issue by SeanPollock** [instantsearch/instantsearch-ion.rangeSlider#2]
Hi,

I wanted to add this repo to jsdeliver to be consistent with the other instantsearch libraries. https://github.com/jsdelivr/jsdelivr/pull/9836#issuecomment-185678664.

A release tag is required, could you add one to the project?

Cheers.

**Comment by redox** [comment]
Definitely!

**Comment by redox** [comment]
Pushed tag `0.1.0`.

**Comment by SeanPollock** [comment]
Awesome, thanks. :)
