### ISSUE TITLE
How to set IonRange plugin's option?

### ISSUE THREAD

**Issue by GlassGruber** [instantsearch/instantsearch-ion.rangeSlider#5]
Hey there!
I'm trying to pass some options from the [plugin docs](http://ionden.com/a/plugins/ion.rangeSlider/en.html) but I can't make it work correctly. Snooping at your code I think the options are passed when the plugin is rendered internally at start, so basically doing something like 

``` javascript
search.addWidget(
  instantsearch.widgets.ionRangeSlider({
    container: '#container',
    attributeName: {
     lowerBound: 'attr_min',
     upperBound: 'attr_max'
    },
    prettify_enabled: false,
  })
);
```

is just ignored AFAICS. Am I missing something? Thank you! :)

**Comment by redox** [comment]
Ah yes indeed, we're rebuilding a `sliderOptions` object that we're passing to the underlying ion.rangeSlider [without forwarding](https://github.com/instantsearch/instantsearch-ion.rangeSlider/blob/master/src/widget.js#L71-L90) extra attributes.

Maybe we can introduce an optional `ionRangeSliderOptions` options that we would use to define `var sliderOptions = $.merge({}, ionRangeSliderOptions, { /* current code defining options */ });`

What do you think?

**Comment by GlassGruber** [comment]
:+1: Yea looks good to me! Thank you for checking this out :)

**Comment by redox** [comment]
Done 👍

**Comment by GlassGruber** [comment]
Working great thanks a lot! :grin:
