### ISSUE TITLE
min / max vaule don't change when the search result change

### ISSUE THREAD

**Issue by terranboy** [instantsearch/instantsearch-ion.rangeSlider#6]
only display the initial value

**Comment by redox** [comment]
Can you share with us the way you're initializing the widget? If you want the `min`, `max` value to change with the results you should not specify them at initialization time.

**Comment by JonnyBR12** [comment]
Have the same question. In my case, there's no min / max specified and the values don't change still. Did anything further happen with this?

**Comment by redox** [comment]
> Have the same question. In my case, there's no min / max specified and the values don't change still. Did anything further happen with this?

Just reproduced it, investigating.

**Comment by redox** [comment]
@JonnyTurnerUK @terranboy should be fixed now :) Available in the 0.2.1 release.

**Comment by JonnyBR12** [comment]
Excellent, thanks @redox
